// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int n = Integer.parseInt(args[0]);
	int a = 0;
	int b = 0;

	for (int i = 0; i <= n; i++){
		double x = Math.random();
		if (x > 0.50) {
			a = a + 1; 
		} else{
			b = b + 1;
		}
	} 
    double ratio; 
	if (a < b) {
		ratio = (double) a / b; 	
	} else{
		ratio = (double) b / a; 
	}

	System.out.println( "> 0.5: " + a + " times");
	System.out.println( "<= 0.5: " + b + " times");
	System.out.println( "Ratio: " + ratio);
	}
	}

